name: Build and push
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Hadolint
      run: |
        curl -sSL https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint
        chmod +x /usr/local/bin/hadolint
    - name: Lint Dockerfile
      run: hadolint Dockerfile
    - name: Build and push Docker image
      shell: bash
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "TAGGED_VERSION=$(< ./version.txt)" >> $GITHUB_ENV
        echo "Tag version is ${TAGGED_VERSION}"
        chmod +x "${GITHUB_WORKSPACE}/util/release.sh"
        bash "${GITHUB_WORKSPACE}/util/release.sh"