name: Build and push
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Hadolint
      run: |
        curl -sSL https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint
        chmod +x /usr/local/bin/hadolint
    - name: Lint Dockerfile
      run: hadolint Dockerfile
    - name: Get tag version
      shell: bash
      run: |
        echo "TAGGED_VERSION<<EOF" >> $GITHUB_OUTPUT
        echo "$(cat ./version.txt)" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      id: version
    - name: Build and push Docker image
      shell: bash
      env:
        TAGGED_VERSION: ${{ steps.version.outputs.TAGGED_VERSION }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Tag version is $TAGGED_VERSION"
        chmod +x "${GITHUB_WORKSPACE}/util/release.sh"
        bash "${GITHUB_WORKSPACE}/util/release.sh"